[variables]
DJANGO_SETTINGS_MODULE = 'construction_site.settings_production'
SECRET_KEY = 'django-insecure-railway-deployment-key-2025'

[phases.build]
cmds = ['pip install -r requirements.txt']

[phases.install]
cmds = [
  'python manage.py collectstatic --noinput',
  'python manage.py migrate --noinput'
]

[start]
cmd = 'gunicorn construction_site.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 30'
