[phases.build]
cmds = ['python -m pip install -r requirements.txt']

[phases.install]
cmds = ['python manage.py collectstatic --noinput']

[start]
cmd = 'python manage.py migrate && gunicorn construction_site.wsgi:application --bind 0.0.0.0:$PORT'
