# Generated by Django 5.2.3 on 2025-07-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Arabic Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Arabic Name'),
        ),
    ]
