# Generated by Django 5.2.3 on 2025-07-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description_ar_product_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Arabic Name'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='value_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Arabic Value'),
        ),
    ]
